function initTranslations(cityTitle, isCityTranslation) {
	var translation = {
		source: {
			title: "Meet and fuck tonight in your area",
			title_replace: "Meet and fuck tonight in " + cityTitle,
			text01: "ATTENTION:",
			text02: "You're Just Seconds Away From Interacting with Real Live Amateurs! Are you 18+ Years Old?",
			text03: "NO",
			text04: "YES",
			text05: "Question 1",
			text06: "Before we can allow you to enter the BIGGEST adult webcam community, we need to ask a few quick questions.",
			text07: "OK",
			text08: "Question 2",
			text09: "Anything can happen on these adult cams, are you OK with watching extremely graphic hardcore sex acts live on cam?",
			text10: "NO",
			text11: "YES",
			text12: "Question 3",
			text13: "Due to past rude behavior, we request that you are not rude to our webcam models. Do you agree?",
			text14: "NO",
			text15: "YES",
			text16: "What is your ideal body type?",
			text17: "(Please choose up to 3 answers)",
			text18: "Thin",
			text19: "Curvy",
			text20: "Big Tits",
			text21: "Big Ass",
			text22: "NEXT",
			text23: "What age group are you most attracted to?",
			text24: "(Please choose up to 3 answers)",
			text25: "NEXT",
			text26: "What is your favorite type of cam show?",
			text27: "(Please choose up to 3 answers)",
			text28: "Private Show",
			text29: "Hidden Cam",
			text30: "Couple Cam",
			text31: "Toy Show/ Squirter",
			text32: "NEXT",
			text33: "What ethnicity do you prefer?",
			text34: "(Please choose up to 3 answers)",
			text35: "White",
			text36: "Asian",
			text37: "Ebony",
			text38: "Other",
			text39: "NEXT",
			text40: "thank you!",
			text41: "You are now ready to create your FREE account. On the next screen, simply choose a username, enter your email address, and begin watching the hottest adult webcams on the Internet! Click on CONTINUE to be taken to the sign-up screen.",
			text42: "Continue",
		},
		en: {
			title: "Meet and fuck tonight in your area",
			title_replace: "Meet and fuck tonight in " + cityTitle,
			text01: "ATTENTION:",
			text02: "You're Just Seconds Away From Interacting with Real Live Amateurs! Are you 18+ Years Old?",
			text03: "NO",
			text04: "YES",
			text05: "Question 1",
			text06: "Before we can allow you to enter the BIGGEST adult webcam community, we need to ask a few quick questions.",
			text07: "OK",
			text08: "Question 2",
			text09: "Anything can happen on these adult cams, are you OK with watching extremely graphic hardcore sex acts live on cam?",
			text10: "NO",
			text11: "YES",
			text12: "Question 3",
			text13: "Due to past rude behavior, we request that you are not rude to our webcam models. Do you agree?",
			text14: "NO",
			text15: "YES",
			text16: "What is your ideal body type?",
			text17: "(Please choose up to 3 answers)",
			text18: "Thin",
			text19: "Curvy",
			text20: "Big Tits",
			text21: "Big Ass",
			text22: "NEXT",
			text23: "What age group are you most attracted to?",
			text24: "(Please choose up to 3 answers)",
			text25: "NEXT",
			text26: "What is your favorite type of cam show?",
			text27: "(Please choose up to 3 answers)",
			text28: "Private Show",
			text29: "Hidden Cam",
			text30: "Couple Cam",
			text31: "Toy Show/ Squirter",
			text32: "NEXT",
			text33: "What ethnicity do you prefer?",
			text34: "(Please choose up to 3 answers)",
			text35: "White",
			text36: "Asian",
			text37: "Ebony",
			text38: "Other",
			text39: "NEXT",
			text40: "thank you!",
			text41: "You are now ready to create your FREE account. On the next screen, simply choose a username, enter your email address, and begin watching the hottest adult webcams on the Internet! Click on CONTINUE to be taken to the sign-up screen.",
			text42: "Continue",
		},
		cs: {
			title: "Seznamte se a zašukejte si ještě dnes večer ve vašem regionu",
			title_replace: "Seznamte se a zašukejte si ještě dnes večer ve " + cityTitle + '?',
			text01: "POZOR:",
			text02: "Od komunikace naživo se skutečnými amatéry vás dělí jen sekundy! Je vám 18 let či více?",
			text03: "Ne",
			text04: "Ano",
			text05: "OTÁZKA 1",
			text06: "Předtím, než vám umožníme vstoupit na NEJVĚTŠÍ komunitu pro dospělé prostřednictvím internetové kamery, se vás musíme zeptat na několik rychlých otázek.",
			text07: "V pořádku",
			text08: "OTÁZKA 2",
			text09: "Bez ohledu na to, co se stane na těchto kamerách pro dospělé, nevadí vám sledování extrémních, grafických, drsných, sexuálních scén naživo na kameře?",
			text10: "Ne",
			text11: "Ano",
			text12: "OTÁZKA 3",
			text13: "Z důvodu hrubého chování v minulosti vás žádáme, abyste nebyli hrubí na naše modely na internetové kameře. Souhlasíte?",
			text14: "Ne",
			text15: "Ano",
			text16: "JAKÝ JE IDEÁLNÍ TYP TĚLA, KTERÝ SE VÁM LÍBÍ?",
			text17: "(VYBERTE AŽ 3 ODPOVĚDI, PROSÍM)",
			text18: "Pohublá",
			text19: "Pěkně stavěná",
			text20: "Velké kozy",
			text21: "Velký zadek",
			text22: "Další",
			text23: "JAKÁ VĚKOVÁ SKUPINA VÁS NEJVÍCE PŘITAHUJE?",
			text24: "(VYBERTE AŽ 3 ODPOVĚDI, PROSÍM)",
			text25: "Další",
			text26: "JAKÝ JE VÁŠ OBLÍBENÝ TYP KAMEROVÉHO PŘEDSTAVENÍ?",
			text27: "(VYBERTE AŽ 3 ODPOVĚDI, PROSÍM)",
			text28: "Soukromá představení",
			text29: "Skrytá kamera",
			text30: "Pár na kameře",
			text31: "Přestavení s hračkami/ mokrý orgasmus",
			text32: "Další",
			text33: "JAKÉ ETNICKÉ PŘÍSLUŠNOSTI DÁVÁTE PŘEDNOST?",
			text34: "(VYBERTE AŽ 3 ODPOVĚDI, PROSÍM)",
			text35: "Bílá",
			text36: "Asijská",
			text37: "černá",
			text38: "Další",
			text39: "Další",
			text40: "DĚKUJEME VÁM!",
			text41: "Nyní jste připraveni si vytvořit váš BEZPLATNÝ účet. Na další obrazovce si jednoduše vyberte uživatelské jméno, zadejte vaši e-mailovou adresu a začněte sledovat nejžhavější internetové kamery pro dospělé na internetu! Klikněte na POKRAČOVAT, abyste přešli na obrazovku přihlášení.",
			text42: "Pokračovat",
		},
		de: {
			title: "Finde ein örtliches Sexdate in deiner Umgebung",
			title_replace: "Finde ein örtliches Sexdate in " + cityTitle,
			text01: "ACHTUNG:",
			text02: "Du bist nur Sekunden davon entfernt, mit echten Amateuren zu interagieren! Bist du 18+ Jahre alt?",
			text03: "Nein",
			text04: "Ja",
			text05: "FRAGE 1",
			text06: "Bevor wir dir den Eintritt in die GRÖSSTE Webcam-Community für Erwachsene ermöglichen können, müssen wir einige kurze Fragen stellen.",
			text07: "OK",
			text08: "FRAGE 2",
			text09: "Auf diesen Cams für Erwachsene kann alles passieren. Sind Sie damit einverstanden, extrem grafische Hardcore-Sex-Acts live vor der Kamera zu sehen?",
			text10: "Nein",
			text11: "Ja",
			text12: "FRAGE 3",
			text13: "Aufgrund von unhöflichem Verhalten in der Vergangenheit bitten wir dich, unseren Webcam-Modellen gegenüber nicht unhöflich zu sein. Bist du einverstanden?",
			text14: "Nein",
			text15: "Ja",
			text16: "WAS IST DDEIN BEVORZUGTER KÖRPERTYP?",
			text17: "(BITTE BIS ZU 3 ANTWORTEN AUSWÄHLEN)",
			text18: "Dünn",
			text19: "Kurvig",
			text20: "Große Titten",
			text21: "Großer Arsch",
			text22: "Weiter",
			text23: "ZU WELCHER ALTERSGRUPPE FÜHLST DU DICH  AM MEISTEN ANGEZOGEN?",
			text24: "(BITTE BIS ZU 3 ANTWORTEN AUSWÄHLEN)",
			text25: "Weiter",
			text26: "WAS IST DEINE LIEBLINGSART VON CAMSHOW?",
			text27: "(BITTE BIS ZU 3 ANTWORTEN AUSWÄHLEN)",
			text28: "Private Show",
			text29: "Versteckte Kamera",
			text30: "Show mit Paaren",
			text31: "Spielzeugshow/ Abspritzen",
			text32: "Weiter",
			text33: "WELCHE ETHNIE BEVORZUGST DU?",
			text34: "(BITTE BIS ZU 3 ANTWORTEN AUSWÄHLEN)",
			text35: "Weiss",
			text36: "Asiaten",
			text37: "Schwarze",
			text38: "Andere",
			text39: "Weiter",
			text40: "DANKE!",
			text41: "Du kannst jetzt dein KOSTENLOSES Konto erstellen. Wähle auf dem nächsten Bildschirm einfach einen Benutzernamen, gebe deine E-Mail-Adresse ein und sschau dir die heißesten Webcams für Erwachsene im Internet an! Klicke auf WEITER, um zum Anmeldebildschirm zu gelangen.",
			text42: "Weiter",
		},
		es: {
			title: "Conoce a alguien y ten sexo esta noche en tu zona",
			title_replace: "Conoce a alguien y ten sexo esta noche en " + cityTitle,
			text01: "ATENCIÓN:",
			text02: "Estás a solo unos segundos de interactuar con amateurs de la vida real! Tienes más de 18 años?",
			text03: "NO",
			text04: "Sí",
			text05: "PREGUNTA 1",
			text06: "Antes de que te permitamos ingresar en la comunidad de webcams para adultos MAS GRANDE, necesitamos hacerte algunas preguntas.",
			text07: "OK",
			text08: "PREGUNTA 2",
			text09: "Todo puede pasar en estas cámaras para adultos, estás de acuerdo en mirar actos sexuales extremadamente gráficos y explícitos en vivo a través de la cámara?",
			text10: "NO",
			text11: "Sí",
			text12: "PREGUNTA 3",
			text13: "Por antecedentes de comportamientos groseros, te solicitamos que no seas grosero con nuestras modelos de webcam. Estás de acuerdo?",
			text14: "NO",
			text15: "Sí",
			text16: "CUÁL ES EL CUERPO IDEAL PARA TI?",
			text17: "(POR FAVOR, ELIGE HASTA 3 RESPUESTAS)",
			text18: "Delgado",
			text19: "Curvilíneo",
			text20: "Tetas grandes",
			text21: "Trasero grande",
			text22: "Siguiente",
			text23: "QUÉ GRUPO ETARIO TE ATRAE MÁS?",
			text24: "(POR FAVOR, ELIGE HASTA 3 RESPUESTAS)",
			text25: "Siguiente",
			text26: "CUÁL ES TU SHOW CAM FAVORITO?",
			text27: "(POR FAVOR, ELIGE HASTA 3 RESPUESTAS)",
			text28: "Show privado",
			text29: "Cámara escondida",
			text30: "Cámara para parejas",
			text31: "Show de juguetes/ eyaculadora",
			text32: "Siguiente",
			text33: "QUÉ GRUPO ÉTNICO PREFIERES?",
			text34: "(POR FAVOR, ELIGE HASTA 3 RESPUESTAS)",
			text35: "Blanco",
			text36: "Asiático",
			text37: "Moreno",
			text38: "Otros",
			text39: "Siguiente",
			text40: "GRACIAS!",
			text41: "Ya estás listo para crear tu cuenta GRATIS. En la siguiente pantalla, solo elige un nombre de usuario, ingresa tu dirección de e-mail y comienza a mirar las webcams para adultos más calientes de Internet! Cliquea CONTINUAR para ir a la pantalla de registro.",
			text42: "Continuar",
		},
		sv: {
			title: "Träffa någon att ha sex med i ditt närområde ikväll",
			title_replace: "Träffa någon att ha sex med ikväll i " + cityTitle,
			text01: "UPPMÄRKSAMHET:",
			text02: "Du är bara några sekunder från att interagera med riktiga liveamatörer! Är du 18+ år?",
			text03: "Nej",
			text04: "Ja",
			text05: "FRÅGA 1",
			text06: "Innan vi kan tillåta dig att gå in i den STÖRSTA webbkameragemenskapen för vuxna måste vi ställa några snabba frågor.",
			text07: "OK",
			text08: "FRÅGA 2",
			text09: "Allt kan hända på dessa vuxenkameror, är du okej med att se extremt grafiska hardcore sexakter live på cam?",
			text10: "Nej",
			text11: "Ja",
			text12: "FRÅGA 3",
			text13: "På grund av tidigare oförskämt beteende ber vi dig att inte vara oförskämd mot våra webbkameramodeller. Håller du med?",
			text14: "Nej",
			text15: "Ja",
			text16: "VAD ÄR DIN IDEELLA KROPPSTYP?",
			text17: "(VÄLJ UPP TILL 3 SVAR)",
			text18: "Tunn",
			text19: "Kurvig",
			text20: "Stora bröst",
			text21: "Big Ass",
			text22: "Nästa",
			text23: "VILKEN ÅLDERSGRUPP ÄR DU MEST ATTRÄNNAD TILL?",
			text24: "(VÄLJ UPP TILL 3 SVAR)",
			text25: "Nästa",
			text26: "VILKEN ÄR DIN FAVORITTYP AV CAM SHOW?",
			text27: "(VÄLJ UPP TILL 3 SVAR)",
			text28: "Privat show",
			text29: "Dold kamera",
			text30: "Par Cam",
			text31: "Toy Show/ Squirter",
			text32: "Nästa",
			text33: "VILKEN ETNICITET FÖREDRAR DU?",
			text34: "(VÄLJ UPP TILL 3 SVAR)",
			text35: "Vit",
			text36: "asiatiska",
			text37: "Ebenholts",
			text38: "Övrig",
			text39: "Nästa",
			text40: "TACK!",
			text41: "Du är nu redo att skapa ditt GRATIS konto. På nästa skärm väljer du bara ett användarnamn, anger din e-postadress och börjar titta på de hetaste webbkamerorna för vuxna på Internet! Klicka på FORTSÄTT för att komma till registreringsskärmen.",
			text42: "Fortsätta",
		},
		da: {
			title: "Mød og have sex i aften i dit område",
			title_replace: "Mød og have sex i aften i " + cityTitle,
			text01: "OPMÆRKSOMHED:",
			text02: "Du er kun få sekunder fra at interagere med rigtige liveamatører! Er du 18+ år?",
			text03: "Godt",
			text04: "Ja",
			text05: "SPØRGSMÅL 1",
			text06: "Før vi kan tillade dig at komme ind i det STØRSTE voksenwebcam-fællesskab, er vi nødt til at stille et par hurtige spørgsmål.",
			text07: "I orden",
			text08: "SPØRGSMÅL 2",
			text09: "Alt kan ske på disse voksenkameraer, er du okay med at se ekstremt grafiske hardcore sexacts live på kamera?",
			text10: "Godt",
			text11: "Ja",
			text12: "SPØRGSMÅL 3",
			text13: "På grund af tidligere uhøflig adfærd anmoder vi om, at du ikke er uhøflig over for vores webcam-modeller. Er du enig?",
			text14: "Godt",
			text15: "Ja",
			text16: "HVAD ER DIN IDEELLE KROPSTYPE?",
			text17: "(VÆLG VENLIGST OP TIL 3 SVAR)",
			text18: "Tynd",
			text19: "Kurvede",
			text20: "Store bryster",
			text21: "Big Ass",
			text22: "Næste",
			text23: "HVILKEN ALDERSGRUPPE ER DU MEST TILTRÆKKET AF?",
			text24: "(VÆLG VENLIGST OP TIL 3 SVAR)",
			text25: "Næste",
			text26: "HVAD ER DIN FAVORITTYPE CAM SHOW?",
			text27: "(VÆLG VENLIGST OP TIL 3 SVAR)",
			text28: "Privat show",
			text29: "Skjult kamera",
			text30: "Par Cam",
			text31: "Legetøjsshow/ Squirter",
			text32: "Næste",
			text33: "HVILKEN ETNICITET FORETRUKKER DU?",
			text34: "(VÆLG VENLIGST OP TIL 3 SVAR)",
			text35: "hvid",
			text36: "Ting",
			text37: "Ibenholt",
			text38: "Andet",
			text39: "Næste",
			text40: "Tak skal du have!",
			text41: "Du er nu klar til at oprette din GRATIS konto. På den næste skærm skal du blot vælge et brugernavn, indtaste din e-mailadresse og begynde at se de hotteste voksenwebcams på internettet! Klik på FORTSÆT for at komme til tilmeldingsskærmen.",
			text42: "Blive ved",
		},
		no: {
			title: "Møt og ha sex i natt i nærheten av deg",
			title_replace: "Møt og ha sex i natt i " + cityTitle,
			text01: "MERK FØLGENDE:",
			text02: "Du er bare sekunder unna å samhandle med ekte liveamatører! Er du 18+ år?",
			text03: "Nei",
			text04: "Ja",
			text05: "SPØRSMÅL 1",
			text06: "Før vi kan tillate deg å gå inn i det STØRSTE voksenwebkamerafellesskapet, må vi stille noen raske spørsmål.",
			text07: "OK",
			text08: "SPØRSMÅL 2",
			text09: "Alt kan skje på disse voksenkameraene, er du OK med å se ekstremt grafiske hardcore sex-akter live på kamera?",
			text10: "Nei",
			text11: "Ja",
			text12: "SPØRSMÅL 3",
			text13: "På grunn av tidligere uhøflig oppførsel ber vi om at du ikke er frekk mot våre webkameramodeller. Er du enig?",
			text14: "Nei",
			text15: "Ja",
			text16: "HVA ER DIN IDEELLE KROPPSTYPE?",
			text17: "(VELG OPP TIL 3 SVAR)",
			text18: "Tynn",
			text19: "Svingete",
			text20: "Store pupper",
			text21: "Big Ass",
			text22: "Neste",
			text23: "HVILKEN ALDERSGRUPPE ER DU MEST TILTREKKET AV?",
			text24: "(VELG OPP TIL 3 SVAR)",
			text25: "Neste",
			text26: "HVA ER DIN FAVORITT TYPE CAM SHOW?",
			text27: "(VELG OPP TIL 3 SVAR)",
			text28: "Privat show",
			text29: "Skjult kamera",
			text30: "Par Cam",
			text31: "Toy Show/ Squirter",
			text32: "Neste",
			text33: "HVILKEN ETNISITET FOREtrekker DU?",
			text34: "(VELG OPP TIL 3 SVAR)",
			text35: "Hvit",
			text36: "asiatisk",
			text37: "Ibenholt",
			text38: "Annen",
			text39: "Neste",
			text40: "TAKK SKAL DU HA!",
			text41: "Du er nå klar til å opprette din GRATIS konto. På den neste skjermen velger du bare et brukernavn, skriver inn e-postadressen din og begynner å se de hotteste voksenwebkameraene på Internett! Klikk på FORTSETT for å komme til registreringsskjermen.",
			text42: "Fortsette",
		},
		fi: {
			title: "Tapaa ja harrasta seksiä alueellasi tänä iltana",
			title_replace: "Tapaa ja harrasta seksiä " + cityTitle + " tänä iltana",
			text01: "HUOMIO:",
			text02: "Olet vain muutaman sekunnin päässä vuorovaikutuksesta todellisten live-amatöörien kanssa! Oletko yli 18-vuotias?",
			text03: "Ei",
			text04: "Joo",
			text05: "KYSYMYS 1",
			text06: "Ennen kuin voimme päästää SUURIN aikuisten verkkokamerayhteisöön, meidän on esitettävä muutama kysymys.",
			text07: "OK",
			text08: "KYSYMYS 2",
			text09: "Mitä tahansa voi tapahtua näissä aikuisten kameroissa, voitko katsoa erittäin graafisia hardcore-seksiä livenä kamerasta?",
			text10: "Ei",
			text11: "Joo",
			text12: "KYSYMYS 3",
			text13: "Aiemman töykeän käytöksen vuoksi pyydämme, että et ole töykeä verkkokameramalleillemme. Oletko samaa mieltä?",
			text14: "Ei",
			text15: "Joo",
			text16: "MIKÄ ON IDEAL VARMOTYYPPISI?",
			text17: "(VALITSE JOPA 3 VASTAUSTA)",
			text18: "Ohut",
			text19: "Kurvikas",
			text20: "Isot Tissit",
			text21: "Iso Ass",
			text22: "Seuraava",
			text23: "MISSÄ IKÄRYHMÄSTÄ VEETÄÄN SINUA ENIMMÄN?",
			text24: "(VALITSE JOPA 3 VASTAUSTA)",
			text25: "Seuraava",
			text26: "MIKÄ ON SUOSIKKI CAM SHOW -TYYPPISI?",
			text27: "(VALITSE JOPA 3 VASTAUSTA)",
			text28: "Yksityinen Show",
			text29: "Piilokamera",
			text30: "Pari Cam",
			text31: "Lelunäyttely/ Squirter",
			text32: "Seuraava",
			text33: "MISTÄ ETNISTÄ KULUA OTAT ennalleen?",
			text34: "(VALITSE JOPA 3 VASTAUSTA)",
			text35: "Valkoinen",
			text36: "asialainen",
			text37: "Eebenpuu",
			text38: "muu",
			text39: "Seuraava",
			text40: "KIITOS!",
			text41: "Olet nyt valmis luomaan ILMAISEN tilisi. Valitse seuraavassa näytössä käyttäjätunnus, kirjoita sähköpostiosoitteesi ja aloita Internetin kuumimpien aikuisten web-kameroiden katselu! Napsauta JATKA päästäksesi kirjautumisnäyttöön.",
			text42: "Jatkaa",
		},
		fr: {
			title: "Rencontrer et baiser ce soir dans votre région",
			title_replace: "Rencontrer et baiser ce soir à " + cityTitle,
			text01: "ATTENTION:",
			text02: "Vous n'êtes qu'à quelques secondes d'interagir avec de vrais amateurs en direct ! Vous avez plus de 18 ans?",
			text03: "Non",
			text04: "Oui",
			text05: "Question 1",
			text06: "Avant de vous permettre d'entrer dans la PLUS GRANDE communauté de webcams pour adultes, nous devons vous poser quelques questions rapides.",
			text07: "OK",
			text08: "Question 2",
			text09: "Tout peut arriver sur ces webcams pour adultes. Êtes-vous prêt à regarder des actes sexuels hardcore extrêmement graphiques en direct sur une webcam?",
			text10: "Non",
			text11: "Oui",
			text12: "Question 3",
			text13: "En raison de comportements antérieurs impolis, nous vous demandons de ne pas être impolis envers nos modèles de webcam. Êtes-vous d'accord?",
			text14: "Non",
			text15: "Oui",
			text16: "QUEL EST VOTRE TYPE DE CORPS IDÉAL?",
			text17: "(VEUILLEZ CHOISIR JUSQU'À 3 RÉPONSES)",
			text18: "Mince",
			text19: "Rondeurs",
			text20: "Gros seins",
			text21: "Gros Cul",
			text22: "Suivant",
			text23: "QUEL EST LE GROUPE D'ÂGE QUI VOUS ATTIRE LE PLUS?",
			text24: "(VEUILLEZ CHOISIR JUSQU'À 3 RÉPONSES)",
			text25: "Suivant",
			text26: "QUEL EST VOTRE TYPE DE CAM SHOW PRÉFÉRÉ?",
			text27: "(VEUILLEZ CHOISIR JUSQU'À 3 RÉPONSES)",
			text28: "Show privé",
			text29: "Caméra cachée",
			text30: "Caméra de couple",
			text31: "Salon du jouet/ Squirter",
			text32: "Suivant",
			text33: "QUELLE ETHNIE PRÉFÉREZ-VOUS?",
			text34: "(VEUILLEZ CHOISIR JUSQU'À 3 RÉPONSES)",
			text35: "Caucasien",
			text36: "Asiatique",
			text37: "Noir",
			text38: "Autre",
			text39: "Suivant",
			text40: "MERCI!",
			text41: "Vous êtes maintenant prêt à créer votre compte GRATUIT. Sur l'écran suivant, choisissez simplement un nom d'utilisateur, entrez votre adresse e-mail et commencez à regarder les webcams pour adultes les plus chaudes d'Internet ! Cliquez sur CONTINUER pour accéder à l'écran d'inscription.",
			text42: "Continuez",
		},
		el: {
			title: "Συνάντησε ντόπια κορίτσια στην περιοχή σου",
			title_replace: "Συνάντησε ντόπια κορίτσια στη " + cityTitle,
			text01: "ΠΡΟΣΟΧΗ:",
			text02: "Απέχεις λίγα δευτερόλεπτα από το να αλληλεπιδράσεις Ζωντανά με Πραγματικές Ερασιτέχνες! Είσαι 18+ ετών;",
			text03: "Όχι",
			text04: "Ναι",
			text05: "1η ΕΡΩΤΗΣΗ",
			text06: "Προτού μπορέσουμε να σου επιτρέψουμε να εισέλθεις στη ΜΕΓΑΛΥΤΕΡΗ κοινότητα διαδικτυακών καμερών για ενήλικες, πρέπει να σου κάνουμε μερικές γρήγορες ερωτήσεις.",
			text07: "OK",
			text08: "2η ΕΡΩΤΗΣΗ",
			text09: "Οτιδήποτε μπορεί να συμβεί σε αυτές τις κάμερες για ενήλικες, είσαι εντάξει με την παρακολούθηση εξαιρετικά γραφικών άγριων σεξουαλικών πράξεων ζωντανά στην κάμερα;",
			text10: "Όχι",
			text11: "Ναι",
			text12: "3η ΕΡΩΤΗΣΗ",
			text13: "Λόγω αγενών συμπεριφορών του παρελθόντος, σου ζητάμε να μην είσαι αγενής με τα μοντέλα των διαδικτυακών μας. Συμφωνείς;",
			text14: "Όχι",
			text15: "Ναι",
			text16: "ΠΟΙΟ ΕΙΝΑΙ Ο ΙΔΑΝΙΚΟΣ ΤΥΠΟΣ ΣΩΜΑΤΟΣ ΓΙΑ ΕΣΕΝΑ;",
			text17: "(ΕΠΕΛΕΞΕ ΕΩΣ 3 ΑΠΑΝΤΗΣΕΙΣ)",
			text18: "Λεπτό",
			text19: "Με καμπύλες",
			text20: "Μεγάλα βυζιά",
			text21: "Μεγάλος κώλος",
			text22: "Επόμενο",
			text23: "ΠΟΙΑ ΗΛΙΚΙΑΚΗ ΟΜΑΔΑ ΣΕ ΕΛΚΥΕΙ ΠΕΡΙΣΣΟΤΕΡΟ;",
			text24: "(ΕΠΕΛΕΞΕ ΕΩΣ 3 ΑΠΑΝΤΗΣΕΙΣ)",
			text25: "Επόμενο",
			text26: "ΠΟΙΟ ΕΙΝΑΙ ΤΟ ΑΓΑΠΗΜΕΝΟ ΣΟΥ ΕΙΔΟΣ ΣΟΟΥ ΣΤΗΝ ΚΑΜΕΡΑ;",
			text27: "(ΕΠΕΛΕΞΕ ΕΩΣ 3 ΑΠΑΝΤΗΣΕΙΣ)",
			text28: "Ιδιωτικό σόου",
			text29: "Κρυφή κάμερα",
			text30: "Κάμερα ζευγαριών",
			text31: "Σόου παιχνιδιών/ Χύσιμο",
			text32: "Επόμενο",
			text33: "ΤΙ ΕΘΝΙΚΟΤΗΤΑ ΠΡΟΤΙΜΑΣ;",
			text34: "(ΕΠΕΛΕΞΕ ΕΩΣ 3 ΑΠΑΝΤΗΣΕΙΣ)",
			text35: "Λευκή",
			text36: "Ασιατική",
			text37: "Μαύρη",
			text38: "Άλλη",
			text39: "Επόμενο",
			text40: "ΕΥΧΑΡΙΣΤΟΥΜΕ!",
			text41: "Είσαι πλέον έτοιμος να δημιουργήσεις τον ΔΩΡΕΑΝ λογαριασμό σου. Στην επόμενη οθόνη, απλώς επέλεξε όνομα χρήστη, πληκτρολόγησε τη διεύθυνση email σου και άρχισε να παρακολουθείς τις πιο δημοφιλείς κάμερες ενηλίκων στο Διαδίκτυο! Κάνε κλικ στο κουμπί ΣΥΝΕΧΕΙΑ για να μεταφερθείς στην οθόνη εγγραφής.",
			text42: "Συνέχεια",
		},
		he: {
			title: "פגוש וזיין הלילה באזורך",
			title_replace: "פגוש וזיין הלילה ב " + cityTitle,
			text01: "שים לב",
			text02: "בעוד שניות אחדות תהיה לך אינטראקציה עם חובבים חיים אמיתיים! האם אתה מעל גיל 18?",
			text03: "לא",
			text04: "כן",
			text05: "שאלה 1",
			text06: "לפני שנוכל לאפשר לך להיכנס לקהילת מצלמות הרשת הגדולה ביותר למבוגרים, נשאל אותך מספר שאלות מהירות.",
			text07: "אוקיי",
			text08: "שאלה 2",
			text09: "הכל יכול לקרות במצלמות המבוגרים, האםמתאים לך לצפות באקטים מיניים גרפיים במיוחד בהארדקור בשידור חי במצלמות?",
			text10: "לא",
			text11: "כן",
			text12: "שאלה 3",
			text13: "בגלל התנהגות גסה בעבר, אנו מבקשים שלא תתנהג בגסות כלפי דגמי מצלמות הרשת שלנו. האם אתה מסכים?",
			text14: "לא",
			text15: "כן",
			text16: "מהו סוג הגוף האידיאלי עבורך?",
			text17: "(נא בחר לכל היותר 3 תשובות)",
			text18: "רזה",
			text19: "חטוב",
			text20: "ציצים גדולים",
			text21: "תחת גדול",
			text22: "הבא",
			text23: "לאיזו קבוצת גיל אתה הכי נמשך?",
			text24: "(נא בחר לכל היותר 3 תשובות)",
			text25: "הבא",
			text26: "מהו סוג תצוגת המצלמות המועדפת עליך?",
			text27: "(נא בחר לכל היותר 3 תשובות)",
			text28: "תצוגה פרטית",
			text29: "מצלמה נסתרת",
			text30: "מצפמה כפולה",
			text31: "מופע צעצועים/ התזה",
			text32: "הבא",
			text33: "איזו קבוצה אתנית אתה מעדיף?",
			text34: "(נא בחר לכל היותר 3 תשובות)",
			text35: "לבן",
			text36: "אסיאתי",
			text37: "כהה עור",
			text38: "אחר",
			text39: "הבא",
			text40: "תודה רבה!",
			text41: "כעת אתה מוכן ליצור את החשבון שלך בחינם. במסך הבא, בחר שם משתמש, הזן את כתובת הדואר האלקטרוני שלך והתחל לצפות במצלמות הרשת החמות ביותר למבוגרים באינטרנט! לחץ על המשךךמעבר למסך ההרשמה.",
			text42: "המשך",
		},
		hr: {
			title: "Upoznajte se i jebite u vašem području",
			title_replace: "Upoznajte se i jebite večeras u " + cityTitle,
			text01: "PAŽNJA:",
			text02: "Samo Vas Sekunde Dijele od Komuniciranja sa Pravim Amaterima Uživo! Da li imate 18+ Godina?",
			text03: "Ne",
			text04: "Da",
			text05: "PITANJE 1",
			text06: "Prije nego što vam dozvolimo da pristupite NAJVEĆEM vebkam društvu za odrasle, moramo vam postaviti nekoliko kratkih pitanja.",
			text07: "OK",
			text08: "PITANJE 2",
			text09: "Sve se može desiti na ovim kamerama za odrasle, da li je OK da gledate ekstremnu hardkor seks akciju uživo na kameri?",
			text10: "Ne",
			text11: "Da",
			text12: "PITANJE 3",
			text13: "Zbog prethodnog lošeg ponašanja, zahtijevamo da ne budete neljubazni prema našim vebkam modelima. Da li se slažete?",
			text14: "Ne",
			text15: "Da",
			text16: "KOJI JE VAŠ IDEALNI TIP TIJELA?",
			text17: "(MOLIMO DA ODABERETE DO 3 ODGOVORA)",
			text18: "Mršavo",
			text19: "Obline",
			text20: "Velike sise",
			text21: "Velika guza",
			text22: "Sljedeće",
			text23: "KOJA STAROSNA DOB VAS NAJVIŠE PRIVLAČI?",
			text24: "(MOLIMO DA ODABERETE DO 3 ODGOVORA)",
			text25: "Sljedeće",
			text26: "KOJA JE VAŠA OMILJENA VRSTA PREDSTAVE NA KAMERAMA?",
			text27: "(MOLIMO DA ODABERETE DO 3 ODGOVORA)",
			text28: "Privatna kamera",
			text29: "Skrivena kamera",
			text30: "Kamera za parove",
			text31: "Šou sa igračkama/ Prskanje",
			text32: "Sljedeće",
			text33: "KOJU ETNIČKU PRIPADNOST PREFERIRATE?",
			text34: "(MOLIMO DA ODABERETE DO 3 ODGOVORA)",
			text35: "Bijelu",
			text36: "Azijatsku",
			text37: "Crnu",
			text38: "Ostalo",
			text39: "Sljedeće",
			text40: "HVALA VAM!",
			text41: "Sada ste spremni da kreirate svoj BESPLATNI nalog. Na sljedećem ekranu, jednostavno izbaerite korisničko ime, unesite svoju email adresu, i počnite gledati najvrelije kamere za odrasle na Internetu. Kliknite DALJE da biste prešli na ekran za upis.", 
			text42: "Dalje",
		},
		hu: {
			title: "Szeretnél meztelen képeket kapni a környékeden élő nőkről?",
			title_replace: "Szeretnél meztelen képeket kapni a " + cityTitle,
			text01: "FIGYELEM:",
			text02: "Másodpercekre vagy attól, hogy Valódi, élő amatőrökkel lépj kapcsolatba! Elmúltál 18 éves?",
			text03: "Nem",
			text04: "Igen",
			text05: "1. KÉRDÉS",
			text06: "Mielőtt engednénk a belépést a LEGNAGYOBB felnőtt webkamera közösséghez, fel kell tennünk néhány gyors kérdést.",
			text07: "Oké",
			text08: "2. KÉRDÉS",
			text09: "Bármi megtörténhet ezeken a felnőtt kamerákon, NEM ZAVAR, ha különösen látványos hardcore szex zajlik élőben a kamerán?",
			text10: "Nem",
			text11: "Igen",
			text12: "3. KÉRDÉS",
			text13: "A korábbi durva viselkedések miatt megköveteljük, hogy ne legyél durva a webkamera modelljeinkkel. Beleegyezel ebbe?",
			text14: "Nem",
			text15: "Igen",
			text16: "MILYEN AZ IDEÁLIS TEST TÍPUSOD?",
			text17: "(KÉRJÜK, VÁLASSZ MAX. 3 VÁLASZT)",
			text18: "Vékony",
			text19: "Telt",
			text20: "Nagy mellek",
			text21: "Nagy fenék",
			text22: "Következő",
			text23: "MELYIK KORCSOPORTHOZ VONZÓDSZ A LEGINKÁBB?",
			text24: "(KÉRJÜK, VÁLASSZ MAX. 3 VÁLASZT)",
			text25: "Következő",
			text26: "MELYIK A KEDVENC KAMERÁS MŰSOR TÍPUSOD?",
			text27: "(KÉRJÜK, VÁLASSZ MAX. 3 VÁLASZT)",
			text28: "Magánműsor",
			text29: "Rejtett kamera",
			text30: "Páros kamera",
			text31: "Játékszer műsor/ spriccelő",
			text32: "Következő",
			text33: "MILYEN ETNIKUMOT PREFERÁLSZ?",
			text34: "(KÉRJÜK, VÁLASSZ MAX. 3 VÁLASZT)",
			text35: "Fehér",
			text36: "Ázsiai",
			text37: "Ébenfekete",
			text38: "Egyéb",
			text39: "Következő",
			text40: "KÖSZÖNJÜK!",
			text41: "Most már készen állsz az INGYENES fiókod létrehozására. A következő képernyőn egyszerűen csak válassz egy felhasználónevet, add meg az e-mail címedet, és kezdd el nézni a legdögösebb felnőtt webkamerákat az Interneten! Kattints a FOLYTATÁSra a regisztrációs képernyőre jutáshoz.",
			text42: "Folytatás",
		},
		it: {
			title: "Incontra persone e scopa stasera nella tua zona",
			title_replace: "Incontra persone e scopa stasera a " + cityTitle,
			text01: "ATTENZIONE:",
			text02: "Tra pochi secondi potrai interagire con veri amatori dal vivo! Hai più di 18 anni?",
			text03: "NO",
			text04: "Sì",
			text05: "DOMANDA 1",
			text06: "Prima di poterti consentire di entrare nella PIÙ GRANDE comunità webcam per adulti, dobbiamo farti alcune brevi domande.",
			text07: "OK",
			text08: "DOMANDA 2",
			text09: "Può succedere di tutto su queste webcam per adulti, accetti di guardare atti sessuali hardcore estremamente forti dal vivo in cam?",
			text10: "NO",
			text11: "Sì",
			text12: "DOMANDA 3",
			text13: "A causa di comportamento spiacevoli rilevati in passato, ti chiediamo di non essere scortese con le nostri modelle in webcam. Sei d'accordo?",
			text14: "NO",
			text15: "Sì",
			text16: "QUAL È IL TUO TIPO DI CORPO IDEALE?",
			text17: "(SCEGLI FINO A 3 RISPOSTE)",
			text18: "Magra",
			text19: "Formosa",
			text20: "Tette grandi",
			text21: "Culo grande",
			text22: "Successivo",
			text23: "A QUALE FASCIA DI ETÀ SEI PIÙ ATTRATTO?",
			text24: "(SCEGLI FINO A 3 RISPOSTE)",
			text25: "Successivo",
			text26: "QUAL È IL TUO TIPO PREFERITO DI SHOW IN CAM?",
			text27: "(SCEGLI FINO A 3 RISPOSTE)",
			text28: "Show privato",
			text29: "Videocamera nascosta",
			text30: "Vieocamera di gruppo",
			text31: "Spettacolo di giochi erotici/ Squirtare",
			text32: "Successivo",
			text33: "QUALE ETNIA PREFERISCI?",
			text34: "(SCEGLI FINO A 3 RISPOSTE)",
			text35: "BIANCA",
			text36: "ASIATICA",
			text37: "NERA",
			text38: "ALTRO",
			text39: "Successivo",
			text40: "GRAZIE!",
			text41: "Ora sei pronto per creare il tuo account GRATUITO. Nella schermata successiva, scegli semplicemente un nome utente, inserisci il tuo indirizzo email e inizia a guardare le webcam per adulti più interessanti su Internet! Clicca su CONTINUA per essere essere reindirizzato alla pagina di registrazione.",
			text42: "Continua",
		},
		ja: {
			title: "あなたの地域で今夜会って性交する",
			title_replace: "今夜会って性交する " + cityTitle,
			text01: "注意：",
			text02: "リアルライブアマチュアと交流するまであと数秒です！ あなたは18歳以上ですか？",
			text03: "いいえ",
			text04: "はい",
			text05: "質問1",
			text06: "最大のアダルトウェブカメラコミュニティへの参加を許可する前に、いくつか簡単な質問にお答えください。",
			text07: "OK",
			text08: "質問2",
			text09: "これらのアダルトカメラで何かが起こる可能性があります。極端に生々しいハードコアセックスをライブカメラで見ても大丈夫ですか?",
			text10: "いいえ",
			text11: "はい",
			text12: "質問3",
			text13: "過去の無礼な行動があっため、ウェブカメラモデルに対して失礼にならないようお願いいたします。 同意していただけますか？",
			text14: "いいえ",
			text15: "はい",
			text16: "あなたの理想の体型は？",
			text17: "(最大3つ選択してください)",
			text18: "瘦せ型",
			text19: "女性らしい体形",
			text20: "巨乳",
			text21: "大きなお尻",
			text22: "次",
			text23: "どの年齢層に最も惹かれますか?",
			text24: "(最大3つ選択してください)",
			text25: "次",
			text26: "あなたの好きなカメラショーのタイプは何ですか?",
			text27: "(最大3つ選択してください)",
			text28: "プライベートショー",
			text29: "隠しカメラ",
			text30: "カップルカメラ",
			text31: "おもちゃショー/ 潮吹き",
			text32: "次",
			text33: "あなたはどの人種を好みますか？",
			text34: "(最大3つ選択してください)",
			text35: "白人",
			text36: "アジア人",
			text37: "黒人",
			text38: "その他",
			text39: "次",
			text40: "ありがとうございます！",
			text41: "無料アカウントを作成する準備ができました。 次の画面で、ユーザー名を選択し、メール アドレスを入力して、インターネットで最もホットなアダルトウェブカメラの視聴を開始します。 [続ける]をクリックすると、登録画面に移動します。",
			text42: "続ける",
		},
		nl: {
			title: "Ontmoet en neuk vanavond in je buurt",
			title_replace: "Ontmoet en neuk vanavond in " + cityTitle,
			text01: "OPGELET:",
			text02: "Je bent slechts enkele seconden verwijderd van interactie met echte live amateurs! Ben je 18+ jaar oud?",
			text03: "Nee",
			text04: "Ja",
			text05: "VRAAG 1",
			text06: "Voordat we je toegang kunnen geven tot de GROOTSTE webcamgemeenschap voor volwassenen, moeten we een paar korte vragen stellen.",
			text07: "OK",
			text08: "VRAAG 2",
			text09: "Er kan van alles gebeuren op deze cams voor volwassenen, vind je het goed om extreem grafische hardcore seksacts live op camera te bekijken?",
			text10: "Nee",
			text11: "Ja",
			text12: "VRAAG 3",
			text13: "Vanwege onbeschoft gedrag in het verleden, verzoeken we je niet onbeleefd te zijn tegen onze webcammodellen. Ga je akkoord?",
			text14: "Nee",
			text15: "Ja",
			text16: "WAT IS JE IDEALE LICHAAMSTYPE?",
			text17: "(KIES MAXIMAAL 3 ANTWOORDEN)",
			text18: "Dun",
			text19: "Vol",
			text20: "Grote tieten",
			text21: "Grote kont",
			text22: "Volgende",
			text23: "WELKE LEEFTIJDSGROEP BEN JE HET MEEST AANGETROKKEN?",
			text24: "(KIES MAXIMAAL 3 ANTWOORDEN)",
			text25: "Volgende",
			text26: "WAT IS JE FAVORIETE TYPE CAM-SHOW?",
			text27: "(KIES MAXIMAAL 3 ANTWOORDEN)",
			text28: "Prive show",
			text29: "Verborgen camera",
			text30: "Koppel-camera",
			text31: "Speelgoedshow/ squirter",
			text32: "Volgende",
			text33: "WELKE ETNICITEIT HEEFT UW VOORKEUR?",
			text34: "(KIES MAXIMAAL 3 ANTWOORDEN)",
			text35: "Wit",
			text36: "Aziatisch",
			text37: "Zwart",
			text38: "Anders",
			text39: "Volgende",
			text40: "BEDANKT!",
			text41: "Je bent nu klaar om je GRATIS account aan te maken. Kies op het volgende scherm een gebruikersnaam, voer je e-mailadres in en begin met het bekijken van de populairste webcams voor volwassenen op internet! Klik op DOORGAAN om naar het aanmeldscherm te gaan.",
			text42: "Doorgaan",
		},
		pl: {
			title: "Poznawaj i bzykaj w Twojej okolicy już dziś",
			title_replace: "Poznawaj i bzykaj we " + cityTitle + " już dziś",
			text01: "UWAGA:",
			text02: "Tylko sekundy dzielą Cię od interakcji z prawdziwymi amatorami na żywo! Czy masz 18 lat?",
			text03: "Nie",
			text04: "Tak",
			text05: "PYTANIE 1",
			text06: "Zanim umożliwimy Ci dołączenie do NAJWIĘKSZEJ społeczności korzystającej z kamerek internetowych dla dorosłych, musimy zadać kilka krótkich pytań.",
			text07: "OK",
			text08: "PYTANIE 2",
			text09: "Wszystko może się zdarzyć na tych kamerach dla dorosłych - czy nie masz nic przeciwko oglądaniu ekstremalnych i hardkorowych aktów seksualnych na żywo przed kamerą?",
			text10: "Nie",
			text11: "Tak",
			text12: "PYTANIE 3",
			text13: "Ze względu na niegrzeczne zachowanie w przeszłości prosimy, abyś nie był niegrzeczny wobec naszych modelek pracujących na kamerkach internetowych. Zgadzasz się?",
			text14: "Nie",
			text15: "Tak",
			text16: "JAKIE JEST TWOJE IDEALNE CIAŁO?",
			text17: "(WYBIERZ MAKS. 3 ODPOWIEDZI)",
			text18: "Chude",
			text19: "Krągłe",
			text20: "Duże cycki",
			text21: "Duży tyłek",
			text22: "Dalej",
			text23: "JAKA GRUPA WIEKOWA NAJBARDZIEJ CIĘ INTERESUJE?",
			text24: "(WYBIERZ MAKS. 3 ODPOWIEDZI)",
			text25: "Dalej",
			text26: "JAKI JEST TWÓJ ULUBIONY SHOW NA KAMERCE INTERNETOWEJ?",
			text27: "(WYBIERZ MAKS. 3 ODPOWIEDZI)",
			text28: "Prywatny show",
			text29: "Ukryta kamera",
			text30: "Para",
			text31: "Z zabawkami/ kobiecy wytrysk",
			text32: "Dalej",
			text33: "JAKĄ GRUPĘ ETNICZNĄ PREFERUJESZ?",
			text34: "(WYBIERZ MAKS. 3 ODPOWIEDZI)",
			text35: "Białe",
			text36: "Azjatki",
			text37: "Murzynki",
			text38: "Inne",
			text39: "Dalej",
			text40: "DZIĘKUJEMY",
			text41: "Możesz teraz utworzyć BEZPŁATNE konto. Na następnym ekranie po prostu wybierz nazwę użytkownika, wprowadź swój adres e-mail i zacznij oglądać najgorętsze kamery internetowe dla dorosłych w Internecie! Kliknij KONTYNUUJ, aby przejść do ekranu rejestracji.",
			text42: "Kontynuuj",
		},
		pt: {
			title: "Tenha um encontro sexual esta noite na sua área",
			title_replace: "Tenha um encontro sexual esta noite em " + cityTitle,
			text01: "ATENÇÃO:",
			text02: "Dentro de segundos estará a interagir com amadores ao vivo! Tem mais de 18 anos?",
			text03: "Não",
			text04: "Sim",
			text05: "PERGUNTA 1",
			text06: "Antes de lhe concedermos entrada na MAIOR comunidade de webcams para adultos, precisamos de lhe colocar algumas perguntas breves.",
			text07: "OK",
			text08: "PERGUNTA 2",
			text09: "Tudo pode acontecer nestas webcams adultas. Sente-se à vontade com a possibilidade de assistir a atos sexuais explícitos extremamente gráficos ao vivo?",
			text10: "Não",
			text11: "Sim",
			text12: "PERGUNTA 3",
			text13: "Devido a comportamento ofensivo no passado, pedimos que não seja mal educado com os nossos modelos. Concorda?",
			text14: "Não",
			text15: "Sim",
			text16: "QUAL É O SEU TIPO DE CORPO IDEAL?",
			text17: "(POR FAVOR ESCOLHA ATÉ 3 RESPOSTAS NO MÁXIMO)",
			text18: "Magro",
			text19: "Curvo",
			text20: "Mamas Grandes",
			text21: "Cu Grande",
			text22: "Seguinte",
			text23: "QUAL É O GRUPO ETÁRIO A QUE SE SENTE MAIS ATRAÍDO?",
			text24: "(POR FAVOR ESCOLHA ATÉ 3 RESPOSTAS NO MÁXIMO)",
			text25: "Seguinte",
			text26: "QUAL É O SEU TIPO DE ESPETÁCULO DE WEBCAM FAVORITO?",
			text27: "(POR FAVOR ESCOLHA ATÉ 3 RESPOSTAS NO MÁXIMO)",
			text28: "Espetáculo Privado",
			text29: "Câmara Oculta",
			text30: "Espetáculo de Casal",
			text31: "Espetáculo de Brinquedos/ Esguichos",
			text32: "Seguinte",
			text33: "QUAL A SUA ETNIA PREFERIDA?",
			text34: "(POR FAVOR ESCOLHA ATÉ 3 RESPOSTAS NO MÁXIMO)",
			text35: "Branca",
			text36: "Asiática",
			text37: "Escura",
			text38: "Outra",
			text39: "Seguinte",
			text40: "OBRIGADO!",
			text41: "Está agora pronto para criar a sua conta GRÁTIS. No próximo ecrã, basta escolher um nome de utilizador, introduzir o seu endereço de e-mail e poderá então começar a visualizar as webcams para adultos mais sensuais da Internet! Faça clique em CONTINUAR para seguir para o ecrã de inscrição.",
			text42: "Continuar",
		},
		ro: {
			title: "Vrei să faci cunoștință cu fete din zona ta?",
			title_replace: "Vrei să faci cunoștință cu fete din " + cityTitle + '?',
			text01: "ATENȚIE:",
			text02: "Ești la doar câteva secunde distanță de interacțiunea cu amatori în carne și oase! Ai peste 18 ani?",
			text03: "Nu",
			text04: "Da",
			text05: "ÎNTREBAREA 1",
			text06: "Înainte de a-ți permite să intri în cea MAI MARE comunitate de camere web pentru adulți, trebuie să-ți punem câteva întrebări rapide.",
			text07: "OK",
			text08: "ÎNTREBAREA 2",
			text09: "Orice se poate întâmpla pe aceste camere pentru adulți, ești de acord cu vizionarea unor acte sexuale hardcore extrem de grafice în direct pe camere?",
			text10: "Nu",
			text11: "Da",
			text12: "ÎNTREBAREA 3",
			text13: "Din cauza unor comportamente nepoliticoase din trecut, te rugăm să nu fii nepoliticos cu modelele noastre de webcam. Ești de acord?",
			text14: "Nu",
			text15: "Da",
			text16: "CARE ESTE TIPUL TĂU IDEAL DE CORP?",
			text17: "(TE RUGĂM ALEGE CEL MULT 3 RĂSPUNSURI)",
			text18: "Subțire",
			text19: "Cu forme",
			text20: "Sâni mari",
			text21: "Fund mare",
			text22: "Înainte",
			text23: "CE GRUPĂ DE VÂRSTĂ TE ATRAGE CEL MAI MULT?",
			text24: "(TE RUGĂM ALEGE CEL MULT 3 RĂSPUNSURI)",
			text25: "Înainte",
			text26: "CARE ESTE TIPUL TĂU PREFERAT DE SPECTACOL PE CAMERĂ?",
			text27: "(TE RUGĂM ALEGE CEL MULT 3 RĂSPUNSURI)",
			text28: "Privat",
			text29: "Cameră ascunsă",
			text30: "Cuplu pe cameră",
			text31: "Spectacol cu jucării sexuale/ Stropitoare",
			text32: "Înainte",
			text33: "CE ETNIE PREFERI?",
			text34: "(TE RUGĂM ALEGE CEL MULT 3 RĂSPUNSURI)",
			text35: "Albă",
			text36: "Asiatică",
			text37: "Abanos",
			text38: "Altele",
			text39: "Înainte",
			text40: "MULȚUMIM!",
			text41: "Acum ești pregătit să îți creezi contul GRATUIT. Pe ecranul următor, trebuie doar să alegi un nume de utilizator, să introduci adresa ta de e-mail și să începi să privești cele mai tari camere web pentru adulți de pe Internet! Fă clic pe CONTINUARE pentru a fi direcționat către ecranul de înscriere.",
			text42: "Continuare",
		},
		ru: {
			title: "Ищешь с кем заняться сексом сегодня в своём городе?",
			title_replace: "Ищешь с кем заняться сексом сегодня в г. " + cityTitle + "?",
			text01: "ВНИМАНИЕ:",
			text02: "Вы всего в нескольких секундах от общения с настоящими любительницами! Вам 18+ лет?",
			text03: "Нет",
			text04: "Да",
			text05: "ВОПРОС 1",
			text06: "Прежде чем мы сможем позволить вам войти в САМОЕ БОЛЬШОЕ сообщество вэб-камс для взрослых, нам нужно задать несколько небольших вопросов.",
			text07: "Ok",
			text08: "ВОПРОС 2",
			text09: "В вэб-кам комнатах для взрослых может случиться что угодно, вы согласны смотреть хардкорное порно в прямом эфире?",
			text10: "Нет",
			text11: "Да",
			text12: "ВОПРОС 3",
			text13: "Из-за грубого поведения в прошлом мы просим вас не грубить нашим вебкам-моделям. Вы согласны?",
			text14: "Нет",
			text15: "Да",
			text16: "КАКОЙ ВАШ ИДЕАЛЬНЫЙ ТИП ТЕЛОСЛОЖЕНИЯ?",
			text17: "(ПОЖАЛУЙСТА, ВЫБЕРИТЕ ДО 3 ОТВЕТОВ)",
			text18: "Худое",
			text19: "Пышное",
			text20: "Большие сиськи",
			text21: "Большая задница",
			text22: "Далее",
			text23: "КАКАЯ ВОЗРАСТНАЯ ГРУППА ПРИВЛЕКАЕТ ВАС БОЛЬШЕ?",
			text24: "(ПОЖАЛУЙСТА, ВЫБЕРИТЕ ДО 3 ОТВЕТОВ)",
			text25: "Далее",
			text26: "КАКОЙ ВАШ ЛЮБИМЫЙ ТИП КАМ-ШОУ?",
			text27: "(ПОЖАЛУЙСТА, ВЫБЕРИТЕ ДО 3 ОТВЕТОВ)",
			text28: "Приват",
			text29: "Скрытая камера",
			text30: "Пара",
			text31: "Шоу игрушек/ сквиртер",
			text32: "Далее",
			text33: "Кого ВЫ ПРЕДПОЧИТАЕТЕ?",
			text34: "(ПОЖАЛУЙСТА, ВЫБЕРИТЕ ДО 3 ОТВЕТОВ)",
			text35: "Белые",
			text36: "Азиатки",
			text37: "Черные",
			text38: "Другая",
			text39: "Далее",
			text40: "СПАСИБО!",
			text41: "Теперь вы готовы создать БЕСПЛАТНУЮ учетную запись. На следующем экране просто выберите имя пользователя, введите свой адрес электронной почты и начните смотреть самые горячие веб-камеры для взрослых в Интернете! Нажмите ПРОДОЛЖИТЬ, чтобы перейти на экран регистрации.",
			text42: "Продолжить",
		},
		sk: {
			title: "Spoznaj niekoho a zašukaj si dnes večer v tvojom okolí",
			title_replace: "Spoznaj niekoho a zašukaj si dnes večer v " + cityTitle,
			text01: "UPOZORNENIE:",
			text02: "Len pár sekúnd vás delí od stretnutia so skutočnými amatérkami! Máte viac ako 18 rokov?",
			text03: "Nie",
			text04: "Áno",
			text05: "OTÁZKA 1",
			text06: "Predtým, ako vám umožníme vstúpiť do NAJVÄČŠEJ komunity s webkamerami pre dospelých, položíme vám niekoľko rýchlych otázok.",
			text07: "OK",
			text08: "OTÁZKA 2",
			text09: "Na týchto kamerách pre dospelých sa môže stať čokoľvek. Súhlasíte so sledovaním extrémne grafického tvrdého sexu naživo na kamere?",
			text10: "Nie",
			text11: "Áno",
			text12: "OTÁZKA 3",
			text13: "Vzhľadom na nevhodné správanie v minulosti vás žiadame, aby ste neboli k našim webkamerovým modelkám neslušný. Súhlasíte?",
			text14: "Nie",
			text15: "Áno",
			text16: "AKÝ JE TYP POSTAVY SA VÁM PÁČI?",
			text17: "(VYBERTE NAJVIAC 3 ODPOVEDE)",
			text18: "Chudá",
			text19: "S krivkami",
			text20: "Veľké prsia",
			text21: "Veľký zadok",
			text22: "Ďalší",
			text23: "AKÁ VEKOVÁ SKUPINA VÁS NAJVIAC LÁKA?",
			text24: "(VYBERTE NAJVIAC 3 ODPOVEDE)",
			text25: "Ďalší",
			text26: "AKÝ JE VÁŠ OBĽÚBENÝ TYP KAMEROVEJ SHOW?",
			text27: "(VYBERTE NAJVIAC 3 ODPOVEDE)",
			text28: "Súkromná",
			text29: "Skrytá kamera",
			text30: "Dvojice",
			text31: "Hračky/ Striekanie",
			text32: "Ďalší",
			text33: "AKÁ ETNICITA SA VÁM PÁČI?",
			text34: "(VYBERTE NAJVIAC 3 ODPOVEDE)",
			text35: "Biela",
			text36: "Aziatka",
			text37: "Černoška",
			text38: "Iná",
			text39: "Ďalší",
			text40: "ĎAKUJEME!",
			text41: "Teraz si môžete vytvoriť účet ZDARMA. Na ďalšej obrazovke si jednoducho vyberte používateľské meno, zadajte svoju e-mailovú adresu a začnite sledovať najpopulárnejšie webové kamery pre dospelých na internete! Kliknutím na POKRAČOVAŤ sa dostanete na obrazovku registrácie.",
			text42: "Pokračovať",
		},
		sl: {
			title: "Spoznajte lokalna dekleta v svojem kraju",
			title_replace: "Spoznajte lokalna dekleta v " + cityTitle,
			text01: "POZOR:",
			text02: "Le še nekaj sekund vas loči od interakcije s pravimi erotičnimi igralkami v živo! Ste starejši od 18 let?",
			text03: "Ne",
			text04: "Da",
			text05: "1. VPRAŠANJE",
			text06: "Preden vam dovolimo vstop v NAJVEČJO skupnost spletnih kamer za odrasle, vam moramo zastaviti nekaj kratkih vprašanj.",
			text07: "V redu",
			text08: "2. VPRAŠANJE",
			text09: "Na teh kamerah za odrasle se lahko zgodi karkoli. Ali se strinjate z gledanjem izjemno nazornih hardcore spolnih dejanj v živo prek kamere?",
			text10: "Ne",
			text11: "Da",
			text12: "3. VPRAŠANJE",
			text13: "Zaradi preteklega nesramnega obnašanja vas prosimo, da do naših modelov na spletnih kamerah niste nesramni. Ali se strinjate?",
			text14: "Ne",
			text15: "Da",
			text16: "KAKŠEN JE VAŠ IDEALEN TIP TELESA?",
			text17: "(IZBERITE NAJVEČ 3 ODGOVORE)",
			text18: "Vitka",
			text19: "Z oblinami",
			text20: "Veliki joški",
			text21: "Velika rit",
			text22: "Naprej",
			text23: "KATERA STAROSTNA SKUPINA VAS NAJBOLJ PRIVLAČI?",
			text24: "(IZBERITE NAJVEČ 3 ODGOVORE)",
			text25: "Naprej",
			text26: "KAKŠNE SPLETNE PREDSTAVE VAS NAJBOLJ PRIVLAČIJO?",
			text27: "(IZBERITE NAJVEČ 3 ODGOVORE)",
			text28: "Zasebna predstava",
			text29: "Skrita kamera",
			text30: "Kamera s parom",
			text31: "Predstava z igračkami/ Squirter",
			text32: "Naprej",
			text33: "KATERA NARODNOST VAM JE NAJBOLJ VŠEČ?",
			text34: "(IZBERITE NAJVEČ 3 ODGOVORE)",
			text35: "Belke",
			text36: "Azijke",
			text37: "Temnopolte",
			text38: "Drugo",
			text39: "NEXT",
			text40: "HVALA!",
			text41: "Zdaj lahko ustvarite svoje BREZPLAČNI račun. Na naslednjem zaslonu preprosto izberite uporabniško ime, vnesite svoj e-naslov in začnite gledati najbolj vroče spletne kamere za odrasle na internetu! Kliknite NADALJUJ, da se vam odpre okno za prijavo.",
			text42: "Nadaljuj",
		},
		tr: {
			title: "Bölgenizde bu gece buluşun ve sevişin",
			title_replace: cityTitle + "'de bu akşam buluşun ve sevişin",
			text01: "DİKKAT:",
			text02: "Gerçek Canlı Amatörlerle Etkileşime Girmenizden Sadece Saniyeler Uzaktasınız! 18+ Yaşında mısınız?",
			text03: "Hayır",
			text04: "Evet",
			text05: "SORU 1",
			text06: "EN BÜYÜK yetişkin web kamerası topluluğuna girmenize izin vermeden önce birkaç kısa soru sormamız gerekiyor.",
			text07: "Tamam",
			text08: "SORU 2",
			text09: "Bu yetişkin kameralarında her şey olabilir, son derece görsel hardcore seks içeriklerini kamerada canlı izlemekte sorun yok mu?",
			text10: "Hayır",
			text11: "Evet",
			text12: "SORU 3",
			text13: "Geçmişteki kaba davranış nedeniyle, web kamerası modellerimize kaba davranmamanızı rica ederiz. Katılıyor musun?",
			text14: "Hayır",
			text15: "Evet",
			text16: "İDEAL VÜCUT TİPİN NEDİR?",
			text17: "(LÜTFEN 3'E KADAR CEVAP SEÇİN)",
			text18: "İnce",
			text19: "Kıvrımlı",
			text20: "Büyük Göğüsler",
			text21: "Büyük Kalça",
			text22: "Sonraki",
			text23: "EN ÇOK HANGİ YAŞ GRUBUNA ÇEKİLİYORSUNUZ?",
			text24: "(LÜTFEN 3'E KADAR CEVAP SEÇİN)",
			text25: "Sonraki",
			text26: "FAVORİ CAM GÖSTERİSİ TÜRÜ NEDİR?",
			text27: "(LÜTFEN 3'E KADAR CEVAP SEÇİN)",
			text28: "Özel gösteri",
			text29: "Gizli Kamera",
			text30: "Çift Kamera",
			text31: "Oyuncak Gösterisi/ Fışkırtma",
			text32: "Sonraki",
			text33: "HANGİ ETNİKİ TERCİH EDİYORSUN?",
			text34: "(LÜTFEN 3'E KADAR CEVAP SEÇİN)",
			text35: "Beyaz",
			text36: "Asya",
			text37: "Siyahi",
			text38: "Diğer",
			text39: "Sonraki",
			text40: "TEŞEKKÜRLER!",
			text41: "Artık ÜCRETSİZ hesabını oluşturmaya hazırsın. Bir sonraki ekranda, bir kullanıcı adı seçin, e-posta adresinizi girin ve İnternet'teki en popüler yetişkin web kameralarını izlemeye başlayın! Kayıt ekranına gitmek için DEVAM'a tıklayın.",
			text42: "Devam",
		},
	};

	var availableLang = translation_available(translation);

	if(!isCityTranslation) {
		for (var x in translation["source"]) {
			replace_text(availableLang, x, translation, isCityTranslation);
		}
	} else {
		var cityArr = ['title_replace', 'text01_replace'];

		for (var x in cityArr) {
			replace_text(availableLang, cityArr[x], translation, isCityTranslation);
		}

		var cityNodes = document.querySelectorAll(".js-geo-city");
		if( translation[browserLang] && cityNodes.length) {
			for (var i = 0; i < cityNodes.length; i++) {
				cityNodes[i].innerHTML = cityTitle;
			}
		}
	}
}

function replace_text(lang, text, translation, isCityTranslation) {
	if (isCityTranslation && text.indexOf('_replace') !== -1) {
		var x = document.getElementById(text.replace('_replace', ''));
	} else {
		var x = document.getElementById(text);
	}

	if (x && translation[lang][text] != undefined) {
		if(x.placeholder != undefined) {
			x.placeholder = translation[lang][text];
		} else if(x.tagName === 'IFRAME') {
			x.src = translation[lang][text];
		} else {
			x.innerHTML = translation[lang][text];
		}
	} else {
		//console.log("element not Found: " + text);
	}
}

function translation_available(objTrls) {
	if (objTrls[browserLang]) {
		return browserLang;
	} else {
		console.log("translation not Found: " + browserLang);
		return "source";
	}
}

function getParameterByName(name) {
	name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
	var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
		results = regex.exec(location.search);
	return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
}

function detect_language() {
	var forceLang = getParameterByName("lang");

	if (forceLang) {
		return forceLang;
	} else {
		var userLang = navigator.languages && navigator.languages[0] || navigator.language || navigator.userLanguage;
		if (userLang == "zh-CN" || userLang == "zh-SG" || userLang == "zh-MY" || userLang == "zh-CHS") {
			userLang = "zh-Hans";
		} else if (userLang == "zh-HK" || userLang == "zh-MO" || userLang == "zh-TW" || userLang == "zh-CHT") {
			userLang = "zh-Hant";
		} else if (userLang == "no" || userLang == "nb" || userLang == "nb-NO" || userLang == "nn-NO") {
			userLang = "no";
		}
		else if (userLang.length > 2) {
			userLang = userLang[0] + userLang[1];
		}
		return userLang;
	}
}

var cityTitle = '';
var browserLang = detect_language();
document.body.classList.add("lang-" + browserLang);

initTranslations(cityTitle, false);

function changeCity(data) {
	data.city["pt"] = data.city["pt-BR"];

	var countryTitle = data.cnames[browserLang] ? data.cnames[browserLang] : data.cnames.en;

	if (!!data.city[browserLang]) {
		var cityTitle = data.city[browserLang];
		initTranslations(cityTitle, true);
	}
}

setTimeout(function() {
	if (geoRefData) {
		changeCity(geoRefData);
	} else {
		var request = new XMLHttpRequest();
		request.open('GET', 'https://data-jsext.com/ExtService.svc/getextparams', true);

		request.onload = function() {
			if (request.status >= 200 && request.status < 400) {
				var data = JSON.parse(request.responseText);
				changeCity(data);
			} else {
				console.log('Server returned an error');
			}
		};

		request.onerror = function() {
			console.log('Error: ' + request.status);
		};

		request.send();
	}
}, 1000);